//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cita
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cita()
        {
            this.Receta = new HashSet<Receta>();
        }
    
        public int IdCita { get; set; }
        public int IdDoctor { get; set; }
        public int IdMascota { get; set; }
        public int IdRecepcionista { get; set; }
        public int IdHistorial { get; set; }
        public System.DateTime Fecha { get; set; }
        public System.TimeSpan Hora { get; set; }
        public string Estado { get; set; }
        public decimal PrecioCita { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Receta> Receta { get; set; }
        public virtual Doctor Doctor { get; set; }
        public virtual HistorialCitas HistorialCitas { get; set; }
        public virtual Mascota Mascota { get; set; }
        public virtual Recepcionista Recepcionista { get; set; }
    }
}
