//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidad
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ClinicaVeterinariaDBEntities : DbContext
    {
        public ClinicaVeterinariaDBEntities()
            : base("name=ClinicaVeterinariaDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cita> Cita { get; set; }
        public virtual DbSet<Doctor> Doctor { get; set; }
        public virtual DbSet<Duenio> Duenio { get; set; }
        public virtual DbSet<HistorialCitas> HistorialCitas { get; set; }
        public virtual DbSet<Mascota> Mascota { get; set; }
        public virtual DbSet<Mes> Mes { get; set; }
        public virtual DbSet<Recepcionista> Recepcionista { get; set; }
        public virtual DbSet<Receta> Receta { get; set; }
    }
}
