//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class Receta
    {
        public int IdReceta { get; set; }
        public string Nombre_Medicamento { get; set; }
        public int Cantidad { get; set; }
        public string Diagnostico { get; set; }
        public string Tratamiento { get; set; }
        public string DuracionTratamiento { get; set; }
        public string DuracionMedicamento { get; set; }
        public int IdCita { get; set; }
    
        public virtual Cita Cita { get; set; }
    }
}
